export interface EmojiPuzzle {
    id: number;
    emojis: string;
    answers: string[];
    category: string;
    hint?: string;
    difficulty: 'easy' | 'medium' | 'hard';
}

export const EMOJI_PUZZLES: EmojiPuzzle[] = [
    { id: 1, emojis: "🟠☝️", answers: ["فالكونز"], category: "كلانات", hint: "أكبر كلان قيمنق في السعودية والشرق الأوسط شعاره برتقالي", difficulty: "medium" },
    { id: 2, emojis: "⚡🔴", answers: ["باور"], category: "كلانات", hint: "كلان قيمنق سعودي شهير يتميز باللون الأحمر والبرق", difficulty: "medium" },
    { id: 3, emojis: "🧠🌀", answers: ["تويستد مايندرز"], category: "كلانات", hint: "كلان سعودي شهير يرمز للعقول الملتوية", difficulty: "medium" },
    { id: 4, emojis: "🎱💚", answers: ["ار ايت"], category: "كلانات", hint: "نادي رياضات إلكترونية سعودي يرمز لرقم 8 ولونه أخضر", difficulty: "medium" },
    { id: 5, emojis: "🤓🎮", answers: ["جيكي"], category: "كلانات", hint: "نادي رياضات إلكترونية معروف بلونه الأصفر ونظارات الجيكس", difficulty: "medium" },
    { id: 6, emojis: "👑🗡️🇸🇦", answers: ["المنتخب السعودي للالعاب الالكترونية"], category: "كلانات", hint: "يمثل المملكة في البطولات الدولية للقيمنق", difficulty: "medium" },
    { id: 7, emojis: "🎮⛏️🧱", answers: ["ماين كرافت"], category: "العاب", hint: "لعبة البناء والكسر الشهيرة", difficulty: "medium" },
    { id: 8, emojis: "🔫🏃‍♂️🛡️", answers: ["ببجي"], category: "العاب", hint: "لعبة باتل رويال شهيرة جداً بالوطن العربي", difficulty: "medium" },
    { id: 9, emojis: "⚽🎮🛡️", answers: ["فيفا"], category: "العاب", hint: "أشهر لعبة كرة قدم إلكترونية", difficulty: "medium" },
    { id: 10, emojis: "🚗⚽💥", answers: ["روكيت ليغ"], category: "العاب", hint: "لعبة كرة قدم بالسيارات", difficulty: "medium" },
    { id: 11, emojis: "🗺️🔫💣", answers: ["كول اوف ديوتي"], category: "العاب", hint: "سلسلة ألعاب حرب شوارع ومنظور أول شهيرة", difficulty: "medium" },
    { id: 12, emojis: "👑🔨🧱", answers: ["فورتنايت"], category: "العاب", hint: "لعبة باتل رويال وبناء شهيرة", difficulty: "medium" },
    { id: 13, emojis: "🚗🔫🕶️", answers: ["قراند"], category: "العاب", hint: "لعبة سرقة السيارات والعالم المفتوح", difficulty: "medium" },
    { id: 14, emojis: "🧙‍♂️⚔️💍", answers: ["الدن رينغ"], category: "العاب", hint: "لعبة سولز صعبة جداً فازت بلعبة السنة", difficulty: "medium" },
    { id: 15, emojis: "🔴🔵🕵️‍♂️", answers: ["امونق اس"], category: "العاب", hint: "لعبة كشف القاتل والمخادع بين أفراد الطاقم", difficulty: "medium" },
    { id: 16, emojis: "🧔🏻‍♂️🍟🎮", answers: ["بندريتا"], category: "ستريمرز", hint: "يوتيوبر سعودي محبوب يشتهر بحبه للبطاطس والقيمنق", difficulty: "medium" },
    { id: 17, emojis: "👑🔫🧔🏻‍♂️", answers: ["شونق"], category: "ستريمرز", hint: "قائد كلان باور وأحد أشهر صانعي محتوى فورتنايت وببجي", difficulty: "medium" },
    { id: 18, emojis: "🧔🏽‍♂️🎁🔥", answers: ["ابو فلة"], category: "ستريمرز", hint: "يوتيوبر يشتهر بحملات التبرع المليونية وابتسامته الشهيرة", difficulty: "medium" },
    { id: 19, emojis: "🧔🏻‍♂️💎⛏️", answers: ["دحومي999"], category: "ستريمرز", hint: "من أقدم وأشهر صناع محتوى ماين كرافت في السعودية", difficulty: "medium" },
    { id: 20, emojis: "🕶️👽🎮", answers: ["اوبلز"], category: "ستريمرز", hint: "يوتيوبر سعودي اشتهر بسلسلة ماين كرافت وألعاب البقاء والفضائيين", difficulty: "medium" },
    { id: 21, emojis: "🕷️🎮🧔🏻‍♂️", answers: ["سبودا"], category: "ستريمرز", hint: "صانع محتوى سعودي يرتبط اسمه برمز العنكبوت", difficulty: "medium" },
    { id: 22, emojis: "🦁🧔🏻‍♂️🎮", answers: ["سولز"], category: "ستريمرز", hint: "ستريمر سعودي شهير بضحكته العالية ولعب فورتنايت", difficulty: "medium" },
    { id: 23, emojis: "🍕🎮🧔🏻‍♂️", answers: ["ملزلز"], category: "ستريمرز", hint: "يوتيوبر سعودي متخصص في ألعاب السولز والتختيم ويحب البيتزا", difficulty: "medium" },
    { id: 24, emojis: "🧔🏻‍♂️🏹🎯", answers: ["راكانو"], category: "ستريمرز", hint: "صانع محتوى سعودي اشتهر باحتراف القوس (الآرتشر) في فورتنايت", difficulty: "medium" },
    { id: 25, emojis: "📺😂🧔🏻‍♂️", answers: ["ابو الرب"], category: "ستريمرز", hint: "يوتيوبر أردني شهير بمقاطع ردات الفعل والتحليلات الكوميدية", difficulty: "medium" },
    { id: 26, emojis: "🧔🏻‍♂️💡🎬", answers: ["اسامة مروة"], category: "ستريمرز", hint: "يوتيوبر عربي يقدم تحديات وفلوقات ذكية وممتعة", difficulty: "medium" },
    { id: 27, emojis: "👓🔬🧔🏻‍♂️", answers: ["الدحيح"], category: "ستريمرز", hint: "صانع محتوى مصري شهير بتبسيط العلوم بطريقة كوميدية", difficulty: "medium" },
    { id: 28, emojis: "🚗🏜️🎥", answers: ["مجرم جيمز"], category: "ستريمرز", hint: "يوتيوبر سعودي من أوائل من قدموا الفلوقات والتحديات الخارجية والسيارات", difficulty: "medium" },
    { id: 29, emojis: "🎥🌍🚶‍♂️", answers: ["جواهر"], category: "ستريمرز", hint: "رحالة ويوتيوبر يصور مغامرات السفر حول العالم", difficulty: "medium" },
    { id: 30, emojis: "🎭🔥🧔🏻‍♂️", answers: ["سيد"], category: "ستريمرز", hint: "صانع محتوى بحريني شهير بألعاب ماين كرافت والتحديات الحماسية", difficulty: "medium" },
    { id: 31, emojis: "🍗🐔🇸🇦", answers: ["البيك"], category: "براندات", hint: "أشهر مطعم دجاج بروستد في السعودية والعالم العربي", difficulty: "medium" },
    { id: 32, emojis: "☕½💰", answers: ["هاف مليون"], category: "براندات", hint: "مقهى سعودي شهير جداً اسمه يعني نصف مليون", difficulty: "medium" },
    { id: 33, emojis: "🛖☕🇸🇦", answers: ["بارنز"], category: "براندات", hint: "من أقدم وأشهر مقاهي القهوة المحلية في السعودية وشعاره الكشك الصغير", difficulty: "medium" },
    { id: 34, emojis: "🌯🇸🇦🔥", answers: ["شاورمر"], category: "براندات", hint: "سلسلة مطاعم سعودية شهيرة متخصصة بالشاورما المبتكرة", difficulty: "medium" },
    { id: 35, emojis: "🍚🍗🇸🇦", answers: ["كبسة"], category: "أكلات", hint: "الأكلة الشعبية الأولى والشهيرة في السعودية", difficulty: "medium" },
    { id: 36, emojis: "🍕🎻🇸🇦", answers: ["مايسترو بيتزا"], category: "براندات", hint: "سلسلة مطاعم بيتزا سعودية شهيرة", difficulty: "medium" },
    { id: 37, emojis: "🐮🥪🇸🇦", answers: ["كودو"], category: "براندات", hint: "مطعم وجبات سريعة سعودي شهير يتميز بتحضير الساندوتش أمامك", difficulty: "medium" },
    { id: 38, emojis: "🐆🍔🇸🇦", answers: ["هرفي"], category: "براندات", hint: "سلسلة مطاعم برجر سعودية قديمة وشهيرة تحمل شعار الفهد", difficulty: "medium" },
    { id: 39, emojis: "🥛🌴🇸🇦", answers: ["المراعي"], category: "براندات", hint: "أكبر شركة ألبان وعصائر في السعودية والشرق الأوسط", difficulty: "medium" },
    { id: 40, emojis: "🍟🍔🤡", answers: ["ماكدونالدز"], category: "براندات", hint: "مطعم الوجبات السريعة العالمي صاحب شعار المهرج وحرف M", difficulty: "medium" },
    { id: 41, emojis: "🍗👴🏼🔴", answers: ["كنتاكي"], category: "براندات", hint: "مطعم بروستد عالمي يرمز له بصورة الكولونيل ساندرز", difficulty: "medium" },
    { id: 42, emojis: "☕️🍩🇺🇸", answers: ["دانكن"], category: "براندات", hint: "سلسلة المقاهي الأمريكية الشهيرة بالدونات والقهوة السوداء", difficulty: "medium" },
    { id: 43, emojis: "🧜‍♀️☕️🟢", answers: ["ستاربكس"], category: "براندات", hint: "أشهر مقهى عالمي يحمل شعار حورية البحر الخضراء", difficulty: "medium" },
    { id: 44, emojis: "🍕🛖🔴", answers: ["بيتزا هت"], category: "براندات", hint: "سلسلة مطاعم بيتزا عالمية تحمل اسم الكوخ", difficulty: "medium" },
    { id: 45, emojis: "🐼🛒🇸🇦", answers: ["بندة"], category: "براندات", hint: "سلسلة أسواق السوبرماركت الشهيرة في السعودية برمز الدب", difficulty: "medium" },
    { id: 46, emojis: "📚📖🇸🇦", answers: ["مكتبة جرير"], category: "براندات", hint: "أشهر معرض للكتاب والأجهزة الإلكترونية في السعودية", difficulty: "medium" },
    { id: 47, emojis: "🧴💊🟢", answers: ["صيدلية النهدي"], category: "براندات", hint: "أكبر سلسلة صيدليات في المملكة العربية السعودية لشعارها هلال أخضر وقطرة", difficulty: "medium" },
    { id: 48, emojis: "🥬🍅🥗", answers: ["فتوش"], category: "أكلات", hint: "سلطة شامية مشهورة تحتوي على قطع الخبز المقرمش", difficulty: "medium" },
    { id: 49, emojis: "🧆🌯🇸🇾", answers: ["فلافل"], category: "أكلات", hint: "أقراص مقلية من الحمص تشتهر في الفطور الشعبي العربي", difficulty: "medium" },
    { id: 50, emojis: "🥩🔥🍢", answers: ["كباب"], category: "أكلات", hint: "لحم مفروم مشوي على السيخ ومعروف في المشويات العربية", difficulty: "medium" },
    { id: 51, emojis: "🗼🥐🎭", answers: ["فرنسا"], category: "دول", hint: "دولة أوروبية تشتهر ببرج إيفل والكرواسون والفنون", difficulty: "medium" },
    { id: 52, emojis: "🇸🇦🏙️🌴", answers: ["الرياض"], category: "مدن", hint: "عاصمة المملكة العربية السعودية ومركز الأبراج والفعاليات", difficulty: "medium" },
    { id: 53, emojis: "🇸🇦🌊⚓", answers: ["جدة"], category: "مدن", hint: "بوابة الحرمين الشريفين والمدينة الساحلية الشهيرة غرب السعودية", difficulty: "medium" },
    { id: 54, emojis: "🇸🇦🕋🕌", answers: ["مكة المكرمة"], category: "مدن", hint: "أقدس بقاع الأرض وبها الكعبة المشرفة", difficulty: "medium" },
    { id: 55, emojis: "🇸🇦🕌🟢", answers: ["المدينة المنورة"], category: "مدن", hint: "بها المسجد النبوي الشريف والقبة الخضراء", difficulty: "medium" },
    { id: 56, emojis: "🇸🇦🌹⛰️", answers: ["الطائف"], category: "مدن", hint: "مدينة جبلية سعودية تشتهر بالورود والجو المعتدل صيفاً", difficulty: "medium" },
    { id: 57, emojis: "🇸🇦⛰️☁️", answers: ["أبها"], category: "مدن", hint: "عاصمة عسير وتشتهر بالجبال والمناظر الطبيعية والضباب", difficulty: "medium" },
    { id: 58, emojis: "🇸🇦🌴🏜️", answers: ["الاحساء"], category: "مدن", hint: "أكبر واحة نخيل في العالم وتقع شرق السعودية", difficulty: "medium" },
    { id: 59, emojis: "🍣🌸🗻", answers: ["اليابان"], category: "دول", hint: "كوكب الشرق الأقصى المشهور بالسوشي وجبل فuji والأنمي", difficulty: "medium" },
    { id: 60, emojis: "📐🏜️🐪", answers: ["مصر"], category: "دول", hint: "بلد الأهرامات والنيل والحضارة الفرعونية", difficulty: "medium" },
    { id: 61, emojis: "🍝🍕🛶", answers: ["ايطاليا"], category: "دول", hint: "دولة أوروبية تشتهر بالباستا والبيتزا والبندقية", difficulty: "medium" },
    { id: 62, emojis: "🎡💂‍♂️🌧️", answers: ["بريطانيا"], category: "دول", hint: "بلد الضباب، مشهور بساعة بيغ بن والحراس البريطانيين", difficulty: "medium" },
    { id: 63, emojis: "🦘🐨🌅", answers: ["استراليا"], category: "دول", hint: "قارة ودولة تشتهر بحيوان الكنغر والكوالا", difficulty: "medium" },
    { id: 64, emojis: "🍁❄️🏒", answers: ["كندا"], category: "دول", hint: "دولة تقع شمال أمريكا تشتهر بورقة القيقب والبرد الشديد", difficulty: "medium" },
    { id: 65, emojis: "🕌🌊🌉", answers: ["تركيا"], category: "دول", hint: "دولة تجمع بين آسيا وأوروبا مشهورة بالقهوة التركية ومضيق البوسفور", difficulty: "medium" },
    { id: 66, emojis: "Taj🥻🕌", answers: ["الهند"], category: "دول", hint: "بلد التوابل والبهارات وموطن تاج محل والبوليوود", difficulty: "medium" },
    { id: 67, emojis: "🐉🥋🇨🇳", answers: ["الصين"], category: "دول", hint: "صاحبة أكبر سور في العالم وتشتهر بالتنانين والكونغ فو", difficulty: "medium" },
    { id: 68, emojis: "🎢🎡🏙️", answers: ["دبي"], category: "مدن", hint: "مدينة إماراتية عالمية تشتهر ببرج خليفة والتطور العمراني", difficulty: "medium" },
    { id: 69, emojis: "🗽🏙️🌭", answers: ["نيويورك"], category: "مدن", hint: "المدينة الأمريكية الشهيرة بتمثال الحرية والتايمز سكوير", difficulty: "medium" },
    { id: 70, emojis: "🐆🏟️⚽", answers: ["البرازيل"], category: "دول", hint: "أكثر دولة فازت بكأس العالم وتشتهر بغابات الأمازون والسامبا", difficulty: "medium" },
    { id: 71, emojis: "🔵🌙⚽", answers: ["الهلال"], category: "اندية", hint: "نادي العاصمة السعودي الملقب بالزعيم ولونه الأزرق", difficulty: "medium" },
    { id: 72, emojis: "💛💙🛡️", answers: ["النصر"], category: "اندية", hint: "نادي العاصمة السعودي الملقب بالعالمي ويلعب له رونالدو", difficulty: "medium" },
    { id: 73, emojis: "🟡⚫🐯", answers: ["الاتحاد"], category: "اندية", hint: "عميد الأندية السعودية في جدة وشعاره النمر الأسود والأصفر", difficulty: "medium" },
    { id: 74, emojis: "💚🛡️🦁", answers: ["الاهلي"], category: "اندية", hint: "قلعة الكؤوس ونادي مدينة جدة الشهير بلونه الأخضر", difficulty: "medium" },
    { id: 75, emojis: "👑⚪⚽", answers: ["ريال مدريد"], category: "اندية", hint: "نادي القرن الأوروبي وصاحب الرقم القياسي بأبطال أوروبا", difficulty: "medium" },
    { id: 76, emojis: "🔴🔵🛡️", answers: ["برشلونة"], category: "اندية", hint: "عملاق إسبانيا الكتالوني ومنافس ريال مدريد التاريخي", difficulty: "medium" },
    { id: 77, emojis: "😈🔴⚽", answers: ["مانشستر يونايتد"], category: "اندية", hint: "النادي الإنجليزي العريق الملقب بالشياطين الحمر", difficulty: "medium" },
    { id: 78, emojis: "🦅🔴🛡️", answers: ["الاهلي المصري"], category: "اندية", hint: "نادي القرن الإفريقي وصاحب الشعبية الكبيرة في مصر والوطن العربي", difficulty: "medium" },
    { id: 79, emojis: "🏹⚪🇪🇬", answers: ["الزمالك"], category: "اندية", hint: "نادي الفن والهندسة المصري وصاحب الشعار الأبيض والخطين الحمر والرامي بالقوس", difficulty: "medium" },
    { id: 80, emojis: "🛥️🔵⚽", answers: ["مانشستر سيتي"], category: "اندية", hint: "بطل إنجلترا الحديث صاحب اللون السماوي وشعار السفينة", difficulty: "medium" },
    { id: 81, emojis: "🏴‍☠️👒🍖", answers: ["ون بيس"], category: "انمي", hint: "أنمي شهير جداً عن القراصنة والبحث عن الكنز الأعظم لقائدهم لوفي", difficulty: "medium" },
    { id: 82, emojis: "🍥🦊🍜", answers: ["ناروتو"], category: "انمي", hint: "أنمي يتحدث عن نينجا بداخله ثعلب ذو ذيول تسعة يحلم أن يصبح الهوكاجي", difficulty: "medium" },
    { id: 83, emojis: "🧗‍♂️⚔️👹", answers: ["هجوم العمالقة"], category: "انمي", hint: "أنمي يحارب فيه البشر كائنات عملاقة خلف ثلاثة أسوار", difficulty: "medium" },
    { id: 84, emojis: "🕵️‍♂️👓⚽", answers: ["المحقق كونان"], category: "انمي", hint: "متحري ذكي يتقلص جسده بفعل عقار سام ويحل القضايا سراً", difficulty: "medium" },
    { id: 85, emojis: "📓🖊️🍎", answers: ["مذكرة الموت"], category: "انمي", hint: "أنمي تدور أحداثه حول دفتر يقتل من يكتب اسمه فيه بمساعدة الشينيغامي", difficulty: "medium" },
    { id: 86, emojis: "🍉📺🇸🇦", answers: ["طاش ما طاش"], category: "مسلسلات", hint: "أشهر مسلسل كوميدي سعودي رمضاني يعالج قضايا المجتمع بطابع فكاهي", difficulty: "medium" },
    { id: 87, emojis: "🏜️🚘🔫", answers: ["رشاش"], category: "مسلسلات", hint: "مسلسل سعودي درامي حظي بشهرة واسعة يدور حول عصابة في الثمانينات", difficulty: "medium" },
    { id: 88, emojis: "👑⚔️🐉", answers: ["صراع العروش"], category: "مسلسلات", hint: "مسلسل فانتازيا عالمي شهير يتنافس فيه الملوك على العرش الحديدي", difficulty: "medium" },
    { id: 89, emojis: "🟢🔴🦑", answers: ["لعبة الحبار"], category: "مسلسلات", hint: "مسلسل كوري يتنافس فيه اللاعبون بملابس رياضية خضراء في ألعاب أطفال مميتة", difficulty: "medium" },
    { id: 90, emojis: "🧪👨‍🔬💵", answers: ["بريكنغ باد"], category: "مسلسلات", hint: "مسلسل عن معلم كيمياء يصاب بالسرطان ويتحول لإنتاج المواد الممنوعة لتأمين عائلته", difficulty: "medium" },
    { id: 91, emojis: "🤡🎈🛶", answers: ["شيء"], category: "افلام", hint: "فيلم رعب شهير يظهر فيه مهرج مرعب يخرج من المجاري بالبالون الأحمر", difficulty: "medium" },
    { id: 92, emojis: "🚢❄️💔", answers: ["تيتانيك"], category: "افلام", hint: "فيلم رومانسي ودرامي تاريخي عن غرق سفينة عملاقة في أول رحلة لها", difficulty: "medium" },
    { id: 93, emojis: "🦁👑🌅", answers: ["الاسد الملك"], category: "افلام", hint: "فيلم ديزني الشهير عن الشبل سيمبا الذي يستعيد عرش والده موفاسا", difficulty: "medium" },
    { id: 94, emojis: "🕷️🕸️🔴", answers: ["سبايدرمان"], category: "افلام", hint: "بطل خارق يكتسب قدرات العنكبوت بعد لدغة من عنكبوت معدل جينياً", difficulty: "medium" },
    { id: 95, emojis: "🦇🌃🛡️", answers: ["باتمان"], category: "افلام", hint: "فارس الظلام الذي يحمي مدينة غوثام مستخدماً ثروته وذكاءه ودون قوى خارقة", difficulty: "medium" },
    { id: 96, emojis: "⚡👓🧙‍♂️", answers: ["هاري بوتر"], category: "افلام", hint: "ساحر صغير يملك ندبة على شكل برق ونظارات مستديرة", difficulty: "medium" },
    { id: 97, emojis: "🥋🐼🥢", answers: ["كونغ فو باندا"], category: "افلام", hint: "دب باندا سمين يصبح التنين المقاتل وبطل الكونغ فو", difficulty: "medium" },
    { id: 98, emojis: "🏎️🏁🔴", answers: ["فيراري"], category: "براندات", hint: "سيارة إيطالية رياضية فاخرة ولونها الأحمر الشهير وشعار الحصان", difficulty: "medium" },
    { id: 99, emojis: "🍎📱💻", answers: ["ابل"], category: "براندات", hint: "أكبر شركة تكنولوجيا في العالم صاحبة الآيفون والماك", difficulty: "medium" },
    { id: 100, emojis: "🌐🔍💻", answers: ["جوجل"], category: "براندات", hint: "أشهر محرك بحث على الإنترنت في العالم", difficulty: "medium" },
    { id: 101, emojis: "🐦🔲💬", answers: ["تويتر"], category: "تطبيقات", hint: "منصة التغريد الشهيرة التي تغير شعارها مؤخراً إلى X", difficulty: "medium" },
    { id: 102, emojis: "📸🎬🔍", answers: ["انستقرام"], category: "تطبيقات", hint: "منصة نشر الصور والفيديوهات القصيرة المملوكة لميتا", difficulty: "medium" },
    { id: 103, emojis: "👻💬💛", answers: ["سناب شات"], category: "تطبيقات", hint: "تطبيق المراسلة والعدسات الشهير باللون الأصفر والشباح الكرتوني", difficulty: "medium" },
    { id: 104, emojis: "🎥🔴🍿", answers: ["يوتيوب"], category: "تطبيقات", hint: "أكبر منصة لمشاهدة ومشاركة الفيديوهات في العالم", difficulty: "medium" },
    { id: 105, emojis: "🎵🎬🕺", answers: ["تيك توك"], category: "تطبيقات", hint: "تطبيق المقاطع الموسيقية والفيديوهات القصيرة الأكثر انتشاراً مؤخراً", difficulty: "medium" },
    { id: 106, emojis: "💬🟢📞", answers: ["واتساب"], category: "تطبيقات", hint: "تطبيق المحادثات الفورية الأكثر استخداماً عالمياً", difficulty: "medium" },
    { id: 107, emojis: "🍿🎬📺", answers: ["نتفليكس"], category: "براندات", hint: "منصة البث المنزلي الشهيرة لإنتاج وتوزيع الأفلام والمسلسلات", difficulty: "medium" },
    { id: 108, emojis: "🎮🟢🗣️", answers: ["ديسكورد"], category: "تطبيقات", hint: "تطبيق المحادثات الصوتية والدردشة المفضل للقيمرز", difficulty: "medium" },
    { id: 109, emojis: "🚙👨‍✈️📦", answers: ["مرسول"], category: "تطبيقات", hint: "تطبيق سعودي شهير لتوصيل الطلبات بأيقونة الطائر الأخضر", difficulty: "medium" },
    { id: 110, emojis: "🐪🇸🇦🌴", answers: ["الجمل"], category: "حيوانات", hint: "سفينة الصحراء والرمز التراثي للمملكة العربية السعودية", difficulty: "medium" },
    { id: 111, emojis: "🦅⛰️👀", answers: ["الصقر"], category: "حيوانات", hint: "طائر جارح يمثل تراث الصقارة والهيبة في شبه الجزيرة العربية", difficulty: "medium" },
    { id: 112, emojis: "🐎🏁🏜️", answers: ["الخيل العربي"], category: "حيوانات", hint: "من أعرق سلالات الخيول في العالم وتشتهر بجمالها وسرعتها", difficulty: "medium" },
    { id: 113, emojis: "🌙⭐🕌", answers: ["رمضان"], category: "منوعات", hint: "شهر الصوم والعبادة عند المسلمين", difficulty: "medium" },
    { id: 114, emojis: "🐑🕋🕋", answers: ["عيد الاضحى"], category: "منوعات", hint: "عيد المسلمين المرتبط بإنهاء شعائر الحج والأضحية", difficulty: "medium" },
    { id: 115, emojis: "🍬🎈🎁", answers: ["عيد الفطر"], category: "منوعات", hint: "العيد الذي يأتي مباشرة بعد انتهاء شهر رمضان المبارك", difficulty: "medium" },
    { id: 116, emojis: "🪵🔥☕", answers: ["شبة نار"], category: "منوعات", hint: "طقس تراثي شتوي في السعودية يجمع الأصدقاء في البر", difficulty: "medium" },
    { id: 117, emojis: "⛺ 🏜️ 🐫", answers: ["الكشتة"], category: "منوعات", hint: "رحلة برية يقوم بها السعوديون للاستمتاع بالطبيعة والهدوء في الشتاء", difficulty: "medium" },
    { id: 118, emojis: "☕🍯🍪", answers: ["الحنيني"], category: "أكلات", hint: "حلوى شتوية سعودية شهيرة مصنوعة من التمر والدقيق والسمن", difficulty: "medium" },
    { id: 119, emojis: "🥐🧈☕", answers: ["كرواسون"], category: "أكلات", hint: "مخبوزات فرنسية هشة على شكل هلال تقدم في الفطور", difficulty: "medium" },
    { id: 120, emojis: "🥞🍯🥞", answers: ["بان كيك"], category: "أكلات", hint: "فطائر دائرية رقيقة تقدم مكدسة مع العسل أو الشوكولاتة في الإفطار", difficulty: "medium" },
    { id: 121, emojis: "🥖🥩🧀", answers: ["ساندوتش فيلي ستيك"], category: "أكلات", hint: "خبز فرنسي محشو بشرائح اللحم البقري والجبن السائل", difficulty: "medium" },
    { id: 122, emojis: "🍟🧂🔴", answers: ["بطاطس ليز"], category: "براندات", hint: "أشهر براند رقائق بطاطس مقرمشة بملح ونكهات متعددة", difficulty: "medium" },
    { id: 123, emojis: "🍫🥛🐮", answers: ["جالاكسي"], category: "براندات", hint: "شوكولاتة ناعمة وحليبية شهيرة جداً بالكراميل أو المكسرات", difficulty: "medium" },
    { id: 124, emojis: "🍦🍧🍨", answers: ["باسكن روبنز"], category: "براندات", hint: "أشهر براند آيس كريم عالمي يشتهر بـ 31 نكهة", difficulty: "medium" },
    { id: 125, emojis: "🍩🍩🍩", answers: ["كندة دونتس"], category: "براندات", hint: "الاسم الشعبي للدوناتس في السعودية والخليج", difficulty: "medium" },
    { id: 126, emojis: "🚙🛒📦", answers: ["نون اكسبرس"], category: "براندات", hint: "شحن وتوصيل نون السريع والشهير بلونه الأصفر", difficulty: "medium" },
    { id: 127, emojis: "🛒🇩🇪🦁", answers: ["سوبرماركت لولو"], category: "براندات", hint: "سلسلة الهايبرماركت الهندية الشهيرة المنتشرة بالخليج", difficulty: "medium" },
    { id: 128, emojis: "🎮👾⚔️", answers: ["بلايستيشن"], category: "براندات", hint: "منصة الألعاب المنزلية الأقوى من سوني", difficulty: "medium" },
    { id: 129, emojis: "🟩🎮🕹️", answers: ["إكس بوكس"], category: "براندات", hint: "منصة الألعاب الشهيرة من شركة مايكروسوفت بلونها الأخضر", difficulty: "medium" },
    { id: 130, emojis: "🟥🎮🍄", answers: ["نينتندو سويتش"], category: "براندات", hint: "منصة ألعاب يابانية هجينة ومحمولة تشتهر بلعبة ماريو", difficulty: "medium" },
    { id: 131, emojis: "👨‍🔧🍄🐢", answers: ["سوبر ماريو"], category: "العاب", hint: "السباك الإيطالي الشهير في عالم الألعاب يبحث عن الأميرة", difficulty: "medium" },
    { id: 132, emojis: "🔵🦔💨", answers: ["سونيك"], category: "العاب", hint: "القنفذ الأزرق السريع في عالم ألعاب سيغا", difficulty: "medium" },
    { id: 133, emojis: "💛⚡🐁", answers: ["بيكاتشو"], category: "انمي", hint: "أشهر بوكيمون لونه أصفر ويطلق صدمات كهربائية", difficulty: "medium" },
    { id: 134, emojis: "🧟‍♂️🧠🔫", answers: ["ريزيدنت ايفل"], category: "العاب", hint: "سلسلة ألعاب رعب البقاء الشهيرة ومواجهة الزومبي", difficulty: "medium" },
    { id: 135, emojis: "👹⚔️🏹", answers: ["إله الحرب"], category: "العاب", hint: "لعبة مغامرات ملحمية بطلها كراتوس وابنه أتريوس", difficulty: "medium" },
    { id: 136, emojis: "🏎️🚦🏁", answers: ["فورمولا 1"], category: "رياضة", hint: "أسرع سباق سيارات في العالم يقام سنوياً في حلبات مخصصة ومنها جدة", difficulty: "medium" },
    { id: 137, emojis: "🏀🔥🗑️", answers: ["دوري كرة السلة الامريكي"], category: "رياضة", hint: "الدوري الأشهر لكرة السلة NBA حول العالم", difficulty: "medium" },
    { id: 138, emojis: "🎾🏆🟢", answers: ["بطولة ويمبلدون"], category: "رياضة", hint: "أقدم بطولة تنس أرضي تلعب على العشب الأخضر ببريطانيا", difficulty: "medium" },
    { id: 139, emojis: "🥊🥇🥊", answers: ["محمد علي كلاي"], category: "منوعات", hint: "أسطورة الملاكمة العالمي المسلم وصاحب اللكمات الأسرع بالتاريخ", difficulty: "medium" },
    { id: 140, emojis: "🏊‍♂️🏅🥇", answers: ["مايكل فيلبس"], category: "منوعات", hint: "السباح الأمريكي صاحب الرقم القياسي في الميداليات الذهبية الأولمبية", difficulty: "medium" },
    { id: 141, emojis: "🇸🇦🏕️🪨", answers: ["العلا"], category: "مدن", hint: "مدينة الآثار والتاريخ والجبال المنحوتة في شمال غرب السعودية", difficulty: "medium" },
    { id: 142, emojis: "🇸🇦🏭🛢️", answers: ["الجبيل"], category: "مدن", hint: "أكبر مدينة صناعية في العالم وتقع في شرق المملكة العربية السعودية", difficulty: "medium" },
    { id: 143, emojis: "🇸🇦❄️⛰️", answers: ["تبوك"], category: "مدن", hint: "مدينة سعودية تقع في الشمال وتشتهر بتساقط الثلوج على جبال اللوز شتاءً", difficulty: "medium" },
    { id: 144, emojis: "🇸🇦🌴🌾", answers: ["القصيم"], category: "مدن", hint: "المنطقة الوسطى الشهيرة بإنتاج وتصدير التمور والزراعة في السعودية", difficulty: "medium" },
    { id: 145, emojis: "🇸🇦⛰️🏹", answers: ["حائل"], category: "مدن", hint: "شمال السعودية وتشتهر بجبل أجا وسلمى وحاتم الطائي الكرم", difficulty: "medium" },
    { id: 146, emojis: "🗻🏂⛄", answers: ["سويسرا"], category: "دول", hint: "دولة أوروبية تشتهر بجبال الألب والشوكولاتة الفاخرة والتزلج", difficulty: "medium" },
    { id: 147, emojis: "🛕🕌🐘", answers: ["تايلاند"], category: "دول", hint: "بلد المعابد والجزر الطبيعية والفيلة في جنوب شرق آسيا", difficulty: "medium" },
    { id: 148, emojis: "🕌🏛️🌴", answers: ["الاردن"], category: "دول", hint: "موطن مدينة البتراء الوردية القديمة ومشهور بالمنسف", difficulty: "medium" },
    { id: 149, emojis: "🕌🍲🇱🇧", answers: ["لبنان"], category: "دول", hint: "بلد الأرز والمأكولات الشامية والجو الجميل والجبال", difficulty: "medium" },
    { id: 150, emojis: "🕋🕌🕊️", answers: ["فلسطين"], category: "دول", hint: "موطن المسجد الأقصى والقدس الشريف", difficulty: "medium" },
    { id: 151, emojis: "🍲🥬🇶🇦", answers: ["قطر"], category: "دول", hint: "شبه جزيرة في الخليج العربي استضافت كأس العالم التاريخي 2022", difficulty: "medium" },
    { id: 152, emojis: "🏙️🛍️🇰🇼", answers: ["الكويت"], category: "دول", hint: "دولة خليجية تشتهر بأبراج الكويت التراثية وسوق المباركية", difficulty: "medium" },
    { id: 153, emojis: "🌴🏰🇴🇲", answers: ["عمان"], category: "دول", hint: "سلطنة تشتهر بجمال طبيعة صلالة والقلاع التراثية وحلوى عمان", difficulty: "medium" },
    { id: 154, emojis: "🏎️🇧🇭🇧🇭", answers: ["البحرين"], category: "دول", hint: "مملكة خليجية تسمى لؤلؤة الخليج وتشتهر بحلبة الصخير للسباقات", difficulty: "medium" },
    { id: 155, emojis: "🏰🕌🇮🇶", answers: ["العراق"], category: "دول", hint: "بلد الرافدين دجلة والفرات والحضارة البابلية القديمة", difficulty: "medium" },
    { id: 156, emojis: "🦁🏞️🐆", answers: ["كينيا"], category: "دول", hint: "دولة إفريقية تشتهر برحلات السفاري البرية والحيوانات المفتوحة", difficulty: "medium" },
    { id: 157, emojis: "🐑🏔️🏞️", answers: ["نيوزيلندا"], category: "دول", hint: "جزيرة هادئة تشتهر بجمال الطبيعة وتصوير فيلم سيد الخواتم بها", difficulty: "medium" },
    { id: 158, emojis: "🧊🐻❄️", answers: ["جرينلاند"], category: "دول", hint: "أكبر جزيرة في العالم تغطيها الثلوج بشكل شبه كامل", difficulty: "medium" },
    { id: 159, emojis: "🏰🧛‍♂️🧛", answers: ["رومانيا"], category: "دول", hint: "دولة تقع شرق أوروبا تشتهر بقصر دراكولا المرعب في ترانسيلفانيا", difficulty: "medium" },
    { id: 160, emojis: "🎡🏙️🇸🇬", answers: ["سنغافورة"], category: "دول", hint: "مدينة ودولة حديثة جداً تشتهر بحدائق الخليج الفائقة التطور وعجلة فيريس", difficulty: "medium" },
    { id: 161, emojis: "🏰🥻🇳🇵", answers: ["نيبال"], category: "دول", hint: "دولة جبلية يقع فيها جبل إيفرست الأعلى في العالم", difficulty: "medium" },
    { id: 162, emojis: "🦒🦁🇿🇦", answers: ["جنوب افريقيا"], category: "دول", hint: "بلد مانديلا والحيوانات البرية وتلتقي فيها محيطات العالم", difficulty: "medium" },
    { id: 163, emojis: "🏜️🕌🇲🇦", answers: ["المغرب"], category: "دول", hint: "بلد الأطلس والمدن القديمة الملونة مثل مراكش والدار البيضاء وشرب الشاي بالنعناع", difficulty: "medium" },
    { id: 164, emojis: "🏛️🏺🇩🇿", answers: ["الجزائر"], category: "دول", hint: "بلد المليون ونصف شهيد وتشتهر بجمال طبيعتها المتنوعة", difficulty: "medium" },
    { id: 165, emojis: "🐫🏜️🇹🇳", answers: ["تونس"], category: "دول", hint: "بلد قرطاج والبيوت البيضاء والزرقاء في سيدي بوسعيد", difficulty: "medium" },
    { id: 166, emojis: "🚢🌾🏜️", answers: ["قناة السويس"], category: "منوعات", hint: "أهم ممر مائي صناعي في العالم يربط البحر الأحمر بالمتوسط بمصر", difficulty: "medium" },
    { id: 167, emojis: "⛰️🧗‍♂️🥶", answers: ["جبل ايفرست"], category: "منوعات", hint: "أعلى قمة جبلية على سطح الأرض في سلسلة جبال الهيمالايا", difficulty: "medium" },
    { id: 168, emojis: "🏞️🌊💦", answers: ["شلالات نياجرا"], category: "منوعات", hint: "أشهر وأقوى شلالات في العالم تقع بين أمريكا وكندا", difficulty: "medium" },
    { id: 169, emojis: "🌴🌊🏖️", answers: ["المالديف"], category: "دول", hint: "جزر استوائية تشتهر بالفنادق المقامة فوق المياه الكريستالية", difficulty: "medium" },
    { id: 170, emojis: "🏰🗿🗿", answers: ["جزيرة الفصح"], category: "منوعات", hint: "جزيرة تشتهر بالتماثيل الحجرية الضخمة الغامضة التي تشبه الوجوه", difficulty: "medium" },
    { id: 171, emojis: "🦜🌴🦟", answers: ["غابات الامازون"], category: "منوعات", hint: "أكبر غابات مطيرة في العالم وتعتبر رئة الأرض", difficulty: "medium" },
    { id: 172, emojis: "🦁🦒🦓", answers: ["حديقة الحيوان"], category: "منوعات", hint: "المكان المخصص لعرض الحيوانات المختلفة للزوار", difficulty: "medium" },
    { id: 173, emojis: "🐬🌊🎡", answers: ["فقيه اكواريوم"], category: "براندات", hint: "المتحف المائي الترفيهي الشهير في كورنيش جدة", difficulty: "medium" },
    { id: 174, emojis: "🎠🎢🎡", answers: ["الشلال تيم بارك"], category: "براندات", hint: "أشهر مدينة ملاهي ترفيهية على ساحل جدة", difficulty: "medium" },
    { id: 175, emojis: "🏙️🛍️🎪", answers: ["بوليفارد سيتي"], category: "براندات", hint: "أضخم منطقة ترفيهية في موسم الرياض تضم مسارح ومطاعم عالمية", difficulty: "medium" },
    { id: 176, emojis: "🎡⛄❄️", answers: ["وندرلاند"], category: "براندات", hint: "مدينة الملاهي الشتوية والألعاب الحماسية الشهيرة بموسم الرياض", difficulty: "medium" },
    { id: 177, emojis: "🚗🛒🇸🇦", answers: ["حراج"], category: "براندات", hint: "أكبر موقع وتطبيق سعودي للبيع والشراء والسيارات المستعملة", difficulty: "medium" },
    { id: 178, emojis: "💼🧑‍💻🇸🇦", answers: ["قوى"], category: "تطبيقات", hint: "منصة سعودية حكومية لتوثيق العقود وإدارة شؤون العمل والموظفين", difficulty: "medium" },
    { id: 179, emojis: "🚗💳🇸🇦", answers: ["نفاذ"], category: "تطبيقات", hint: "تطبيق الدخول الوطني الموحد للهوية السعودية الإلكترونية", difficulty: "medium" },
    { id: 180, emojis: "🛡️👨‍✈️🇸🇦", answers: ["ابشر"], category: "تطبيقات", hint: "أشهر منصة خدمات حكومية إلكترونية للمواطنين والمقيمين في السعودية", difficulty: "medium" },
    { id: 181, emojis: "🩺🏥🇸🇦", answers: ["صحتي"], category: "تطبيقات", hint: "تطبيق وزارة الصحة السعودية لحجز المواعيد والتقارير الطبية", difficulty: "medium" },
    { id: 182, emojis: "🚌🎒🇸🇦", answers: ["مدرستي"], category: "تطبيقات", hint: "منصة التعليم عن بعد الحكومية في السعودية للطلاب والمعلمين", difficulty: "medium" },
    { id: 183, emojis: "🕋🕌📖", answers: ["توكلنا"], category: "تطبيقات", hint: "التطبيق السعودي الشهير الذي يضم الهويات وخدمات الحج والعمرة والأنشطة", difficulty: "medium" },
    { id: 184, emojis: "📱💳💵", answers: ["مدى"], category: "براندات", hint: "شبكة الدفع الإلكتروني المعتمدة والأشهر في نقاط البيع السعودية", difficulty: "medium" },
    { id: 185, emojis: "🏠📦🛋️", answers: ["ابيات السعودية"], category: "براندات", hint: "شركة كويتية متخصصة في الأثاث والمواد الإنشائية لها فروع بالرياض وجدة", difficulty: "medium" },
    { id: 186, emojis: "🛏️🛋️🇸🇪", answers: ["ايكيا"], category: "براندات", hint: "سلسلة السويد العالمية للأثاث المجهز بالتركيب والوجبات السويدية بالمعرض", difficulty: "medium" },
    { id: 187, emojis: "🏠🛋️🛋️", answers: ["هوم بوكس"], category: "براندات", hint: "معرض أثاث منزلي بأسعار اقتصادية ينتشر في مولات السعودية", difficulty: "medium" },
    { id: 188, emojis: "🧴💅🛍️", answers: ["نايس ون"], category: "براندات", hint: "تطبيق مكياج وعطور سعودي رائد حظي بشهرة سريعة", difficulty: "medium" },
    { id: 189, emojis: "🧴💅🇺🇸", answers: ["سيفورا"], category: "براندات", hint: "أشهر براند مستحضرات تجميل ومكياج فرنسي يضم ماركات عالمية", difficulty: "medium" },
    { id: 190, emojis: "🧥👗👞", answers: ["نمشي"], category: "براندات", hint: "تطبيق رائد للأزياء والملابس والأحذية بالشرق الأوسط", difficulty: "medium" },
    { id: 191, emojis: "📖📝🎒", answers: ["شنطة المدرسة"], category: "منوعات", hint: "حقيبة يحملها الطلاب يومياً لحفظ الكتب والدفاتر", difficulty: "medium" },
    { id: 192, emojis: "🕶️☀️🏖️", answers: ["نظارة شمسية"], category: "منوعات", hint: "تلبس لحماية العين من أشعة الشمس القوية في الصيف", difficulty: "medium" },
    { id: 193, emojis: "🧴☀️🏖️", answers: ["واقي شمس"], category: "منوعات", hint: "كريم يوضع على البشرة لمنع الحروق الناتجة عن شمس الصيف", difficulty: "medium" },
    { id: 194, emojis: "🍉🧊🏖️", answers: ["جح بارد"], category: "أكلات", hint: "فاكهة الصيف المفضلة في السعودية لإطفاء العطش والحر", difficulty: "medium" },
    { id: 195, emojis: "🥛🌾🍪", answers: ["معمول"], category: "أكلات", hint: "حلوى سعودية تقليدية محشوة بالتمر تقدم بجانب القهوة السعودية في الأعياد", difficulty: "medium" },
    { id: 196, emojis: "🍵🇸🇦🌾", answers: ["قهوة سعودية"], category: "أكلات", hint: "القهوة العربية الصفراء المضاف إليها الهيل والزعفران رمز الكرم", difficulty: "medium" },
    { id: 197, emojis: "🍵🪵💚", answers: ["شاي اخضر"], category: "أكلات", hint: "مشروب ساخن شهير بفوائده الصحية ويقدم بعد الوجبات الدسمة للتخسيس", difficulty: "medium" },
    { id: 198, emojis: "🍵🌿🍃", answers: ["نعناع المدينة"], category: "أكلات", hint: "أشهر أنواع النعناع في السعودية يضاف إلى الشاي الأحمر", difficulty: "medium" },
    { id: 199, emojis: "🐑🧅🥣", answers: ["شوربة جريش"], category: "أكلات", hint: "شوربة شعبية سعودية مشهورة في فطور شهر رمضان", difficulty: "medium" },
    { id: 200, emojis: "🍞🥩🧅", answers: ["مطازيز"], category: "أكلات", hint: "أكلة شعبية نجدية من رقائق العجين واللحم والخضار بمرق ثقيل", difficulty: "medium" },
    { id: 201, emojis: "🍲🍖🌾", answers: ["سليق طائفي"], category: "أكلات", hint: "أكلة حجازية شعبية تشبه الأرز بالحليب وتقدم مع دجاج أو لحم", difficulty: "medium" },
    { id: 202, emojis: "🍚🥩🍠", answers: ["مندي"], category: "أكلات", hint: "طريقة طبخ اللحم في حفرة تحت الأرض ليكون طرياً جداً مع الأرز", difficulty: "medium" },
    { id: 203, emojis: "🍗🍠🍖", answers: ["مظبي"], category: "أكلات", hint: "لحم أو دجاج يشوى على حجارة نظيفة ساخنة", difficulty: "medium" },
    { id: 204, emojis: "🐟🍤🧅", answers: ["مطبق سمك"], category: "أكلات", hint: "أرز مطبوخ مع قطع السمك المتبل ومزين بالبصل المقلي والتوابل", difficulty: "medium" },
    { id: 205, emojis: "🍞🥣🍯", answers: ["عريكة"], category: "أكلات", hint: "أكلة جنوبية دسمة جداً من البر والسمن والعسل والتمر", difficulty: "medium" },
    { id: 206, emojis: "🥐🌾🍯", answers: ["مشغوثة"], category: "أكلات", hint: "حلوى جنوبية تقدم ساخنة مع التمر والسمن البري في الشتاء", difficulty: "medium" },
    { id: 207, emojis: "🐟🔥🍋", answers: ["سمك مشوي"], category: "أكلات", hint: "وجبة ساحلية مفضلة في مدن جدة والدمام وينبع", difficulty: "medium" },
    { id: 208, emojis: "🍤🧅🍚", answers: ["صيادية"], category: "أكلات", hint: "أرز بني مطبوخ ببصل محروق يقدم بجانب السمك المقلي أو المشوي", difficulty: "medium" },
    { id: 209, emojis: "🍞🥩🥙", answers: ["مطبق"], category: "أكلات", hint: "عجين رقيق محشو باللحم المفروم والكرات والبيض ومطبوخ على الصاج", difficulty: "medium" },
    { id: 210, emojis: "🍞🍯🧈", answers: ["معصوب"], category: "أكلات", hint: "موز مهروس مع خبز بر وسمن وعسل وقشطة يعتبر فطور طاقة شهير", difficulty: "medium" },
    { id: 211, emojis: "🥣🥛🐑", answers: ["جريش نجد"], category: "أكلات", hint: "حبوب القمح المجروشة المطبوخة باللبن والمرق ومزينة بالبصل والسمن", difficulty: "medium" },
    { id: 212, emojis: "🍞🧅🥔", answers: ["مرقوق"], category: "أكلات", hint: "عجين يرق ويوضع في مرق اللحم والخضار حتى ينضج", difficulty: "medium" },
    { id: 213, emojis: "🍉🍉🥤", answers: ["عصير جح"], category: "أكلات", hint: "مشروب منعش جداً يقدم مثلجاً في الصيف الحار", difficulty: "medium" },
    { id: 214, emojis: "🍋🌿🥤", answers: ["ليمون بالنعناع"], category: "أكلات", hint: "المشروب الكلاسيكي المنعش لإعادة الحيوية بعد حر الصيف", difficulty: "medium" },
    { id: 215, emojis: "🥑🍯🥛", answers: ["عصير افوكادو"], category: "أكلات", hint: "عصير كريمي غني بالدهون المفيدة يقدم مع العسل والمكسرات", difficulty: "medium" },
    { id: 216, emojis: "🥭🥛🧊", answers: ["عصير مانجو"], category: "أكلات", hint: "أشهر عصير فاكهة استوائية محبوب وحلو المذاق", difficulty: "medium" },
    { id: 217, emojis: "🥤🍪🧊", answers: ["ميلك شيك"], category: "أكلات", hint: "مخفوق الحليب والآيس كريم بنكهة الأوريو أو الفانيليا", difficulty: "medium" },
    { id: 218, emojis: "☕🥛🍫", answers: ["سبانيش لاتيه"], category: "أكلات", hint: "قهوة باردة شهيرة بمذاقها الحلو بفضل الحليب المكثف المحلي", difficulty: "medium" },
    { id: 219, emojis: "☕🥛🧊", answers: ["ايس لاتيه"], category: "أكلات", hint: "قهوة إسبريسو وحليب بارد مع قطع الثلج", difficulty: "medium" },
    { id: 220, emojis: "🍋🧊🫐", answers: ["موهيتو"], category: "أكلات", hint: "مشروب غازي مثلج ومحلى بنكهة التوت البري والليمون والنعناع", difficulty: "medium" },
    { id: 221, emojis: "⚡🥤🧊", answers: ["كودرد"], category: "براندات", hint: "مشروب الطاقة السعودي الشهير بخلطه مع نكهات مختلفة ونعناع", difficulty: "medium" },
    { id: 222, emojis: "🥫🔴🥤", answers: ["كوكاكولا"], category: "براندات", hint: "أشهر مشروب غازي عالمي في علبة حمراء شهيرة", difficulty: "medium" },
    { id: 223, emojis: "🥫🔵🥤", answers: ["ببسي"], category: "براندات", hint: "المنافس اللدود لكوكاكولا في علبته الزرقاء الشهيرة", difficulty: "medium" },
    { id: 224, emojis: "🥫🟢🥤", answers: ["سفن اب"], category: "براندات", hint: "مشروب غازي شفاف بنكهة الليمون والليمون الحامض", difficulty: "medium" },
    { id: 225, emojis: "🥫🟠🥤", answers: ["ميرندا حمضيات"], category: "براندات", hint: "المشروب الغازي المفضل لدى فئة كبيرة من المراهقين بالسعودية", difficulty: "medium" },
    { id: 226, emojis: "🥕🍊🥤", answers: ["عصير برتقال وجزر"], category: "أكلات", hint: "مزيج صحي غني بفيتامين سي والبيتا كاروتين يقدم صباحاً", difficulty: "medium" },
    { id: 227, emojis: "🍍🥥🥤", answers: ["بينا كولادا"], category: "أكلات", hint: "مزيج عصير الأناناس الكريمي مع حليب جوز الهند والثلج", difficulty: "medium" },
    { id: 228, emojis: "🍎🍷🧊", answers: ["سعودي شامبين"], category: "أكلات", hint: "مشروب عصير تفاح فوار يقدم في الحفلات والمطاعم مع قطع الفواكه الطازجة والنعناع", difficulty: "medium" },
    { id: 229, emojis: "🌾🥛🍲", answers: ["المهلبية"], category: "أكلات", hint: "حلوى حليب ونشا باردة تزين بالفستق المبشور", difficulty: "medium" },
    { id: 230, emojis: "📺📱⚽", answers: ["بي ان سبورت"], category: "براندات", hint: "شبكة القنوات الرياضية الأشهر في الشرق الأوسط", difficulty: "medium" },
    { id: 231, emojis: "🔵💬🦅", answers: ["تيليجرام"], category: "تطبيقات", hint: "تطبيق محادثات يتميز بالقنوات وسرعة الإرسال", difficulty: "medium" },
    { id: 232, emojis: "🎥🎬🍿", answers: ["شاهد"], category: "تطبيقات", hint: "أكبر منصة عربية لمشاهدة المسلسلات والأفلام", difficulty: "medium" },
    { id: 233, emojis: "🚕📱👨‍✈️", answers: ["اوبر"], category: "تطبيقات", hint: "تطبيق طلب السيارات للتوصيل الأشهر عالمياً", difficulty: "medium" },
    { id: 234, emojis: "🟢🚕📱", answers: ["كريم"], category: "تطبيقات", hint: "تطبيق توصيل سيارات رائد في الشرق الأوسط استحوذت عليه أوبر", difficulty: "medium" },
    { id: 235, emojis: "🛵📦🍔", answers: ["جاهز"], category: "تطبيقات", hint: "تطبيق سعودي شهير لتوصيل الطلبات والمطاعم لونه أحمر", difficulty: "medium" },
    { id: 236, emojis: "🍔🛵🟡", answers: ["هنقرستيشن"], category: "تطبيقات", hint: "أول وأشهر تطبيق توصيل طلبات مطاعم في السعودية", difficulty: "medium" },
    { id: 237, emojis: "🏠🛠️📱", answers: ["مستقل"], category: "تطبيقات", hint: "منصة عربية رائدة للعمل الحر وتقديم الخدمات", difficulty: "medium" },
    { id: 238, emojis: "💼🤝🌐", answers: ["لينكد ان"], category: "تطبيقات", hint: "منصة التواصل الاجتماعي المهنية للوظائف والأعمال", difficulty: "medium" },
    { id: 239, emojis: "📷👻💬", answers: ["سناب شات"], category: "تطبيقات", hint: "تطبيق التواصل المفضل لالتقاط اليوميات بالفلتر", difficulty: "medium" },
    { id: 240, emojis: "📱🎮⛏️", answers: ["روبلوكس"], category: "العاب", hint: "لعبة مجتمعية ضخمة تتيح للاعبين تصميم ألعابهم الخاصة", difficulty: "medium" },
    { id: 241, emojis: "🪂🔫🗺️", answers: ["فورتنايت"], category: "العاب", hint: "لعبة الباتل رويال الشهيرة التي يتنافس فيها 100 لاعب", difficulty: "medium" },
    { id: 242, emojis: "🔫🛡️💣", answers: ["فالورانت"], category: "العاب", hint: "لعبة تصويب تكتيكية شهيرة من شركة رايوت قيمز", difficulty: "medium" },
    { id: 243, emojis: "⚔️🧙‍♂️🗺️", answers: ["ليق اوف ليجيندز"], category: "العاب", hint: "لعبة الموبا (MOBA) الأشهر في عالم الرياضات الإلكترونية", difficulty: "medium" },
    { id: 244, emojis: "⚽🏎️🚀", answers: ["روكيت ليق"], category: "العاب", hint: "كرة قدم تلعب بالسيارات الصاروخية", difficulty: "medium" },
    { id: 245, emojis: "🧱⛏️🟩", answers: ["ماين كرافت"], category: "العاب", hint: "لعبة البناء والنجاة بالعالم المفتوح المكون من المكعبات", difficulty: "medium" },
    { id: 246, emojis: "🚗🔫🚓", answers: ["جراند ثيفت اوتو"], category: "العاب", hint: "لعبة سرقة السيارات والعصابات الشهيرة", difficulty: "medium" },
    { id: 247, emojis: "🕵️‍♂️🔪🔴", answers: ["امونج اس"], category: "العاب", hint: "لعبة الخداع واكتشاف القاتل بين أفراد الطاقم الفضائي", difficulty: "medium" },
    { id: 248, emojis: "🏃‍♂️💨🔵", answers: ["سونيك"], category: "العاب", hint: "القنفذ الأزرق الأسرع في عالم الألعاب", difficulty: "medium" },
    { id: 249, emojis: "🍄🐢👨‍🔧", answers: ["سوبر ماريو"], category: "العاب", hint: "السباك الإيطالي الشهير في عالم الألعاب يبحث عن الأميرة", difficulty: "medium" },
    { id: 250, emojis: "🧟‍♂️🔫🏙️", answers: ["ليفت فور ديد"], category: "العاب", hint: "لعبة إطلاق نار تعاونية ضد حشود الزومبي", difficulty: "medium" },
    { id: 251, emojis: "🦖🏝️🔫", answers: ["ارك"], category: "العاب", hint: "لعبة بقاء وترويض ديناصورات في جزيرة غامضة", difficulty: "medium" },
    { id: 252, emojis: "🤠🐎🔫", answers: ["ريد ديد ريدمبشن"], category: "العاب", hint: "لعبة الغرب الأمريكي الشهيرة وقصة عصابة داتش فانديرلاند", difficulty: "medium" },
    { id: 253, emojis: "🏹🤖🌍", answers: ["هورايزون"], category: "العاب", hint: "لعبة مغامرات في عالم ما بعد الكارثة تسيطر عليه آلات تشبه الديناصورات", difficulty: "medium" },
    { id: 254, emojis: "⚔️👹🛡️", answers: ["دارك سولز"], category: "العاب", hint: "سلسلة ألعاب تقمص أدوار صعبة جداً تعاقب اللاعب على أخطائه", difficulty: "medium" },
    { id: 255, emojis: "👻🔦🏠", answers: ["فازموفوبيا"], category: "العاب", hint: "لعبة رعب تعاونية للبحث عن الأشباح باستخدام أدوات التحقيق", difficulty: "medium" },
    { id: 256, emojis: "🏎️🚦🏁", answers: ["نيد فور سبيد"], category: "العاب", hint: "سلسلة ألعاب سباق السيارات الشهيرة والمطاردات مع الشرطة", difficulty: "medium" },
    { id: 257, emojis: "👊🔥🐉", answers: ["تيكن"], category: "العاب", hint: "سلسلة ألعاب قتال يابانية شهيرة جداً", difficulty: "medium" },
    { id: 258, emojis: "🩸💀👊", answers: ["مورتال كومبات"], category: "العاب", hint: "لعبة قتال دموية شهيرة بالضربات القاضية 'الفيتاليتي'", difficulty: "medium" },
    { id: 259, emojis: "🕷️🕸️🏙️", answers: ["سبايدر مان"], category: "العاب", hint: "لعبة حصرية للبلايستيشن يتأرجح فيها بطل مارفل في شوارع نيويورك", difficulty: "medium" },
    { id: 260, emojis: "⚽👟🥅", answers: ["كأس العالم"], category: "رياضة", hint: "البطولة الكروية الأهم عالمياً والتي تقام كل 4 سنوات", difficulty: "medium" },
    { id: 261, emojis: "🏀⛹️‍♂️🏆", answers: ["دوري ابطال اوروبا"], category: "رياضة", hint: "أقوى بطولة للأندية في كرة القدم الأوروبية", difficulty: "medium" },
    { id: 262, emojis: "🥊🥇🥊", answers: ["محمد علي كلاي"], category: "رياضة", hint: "أسطورة الملاكمة العالمي المسلم وصاحب اللكمات الأسرع بالتاريخ", difficulty: "medium" },
    { id: 263, emojis: "🎾🏆🟢", answers: ["بطولة ويمبلدون"], category: "رياضة", hint: "أقدم بطولة تنس أرضي تلعب على العشب الأخضر ببريطانيا", difficulty: "medium" },
    { id: 264, emojis: "🏎️🏁🏎️", answers: ["فورمولا ون"], category: "رياضة", hint: "أسرع سباقات السيارات في العالم", difficulty: "medium" },
    { id: 265, emojis: "🏂❄️🏔️", answers: ["تزلج على الجليد"], category: "رياضة", hint: "رياضة شتوية ممتعة تعتمد على الانزلاق على المنحدرات الثلجية", difficulty: "medium" },
    { id: 266, emojis: "🏄‍♂️🌊🏄‍♀️", answers: ["ركوب الامواج"], category: "رياضة", hint: "رياضة مائية تعتمد على التوازن على لوح خشبي فوق الموج", difficulty: "medium" },
    { id: 267, emojis: "🏋️‍♂️💪🥇", answers: ["رفع الاثقال"], category: "رياضة", hint: "رياضة أولمبية تتطلب قوة بدنية عالية لرفع أوزان ثقيلة", difficulty: "medium" },
    { id: 268, emojis: "🚴‍♂️🚵‍♂️🏔️", answers: ["سباق الدراجات"], category: "رياضة", hint: "رياضة ركوب الدراجات الهوائية في المسارات المخصصة", difficulty: "medium" },
    { id: 269, emojis: "🏊‍♂️🏅🥇", answers: ["السباحة"], category: "رياضة", hint: "رياضة مائية أولمبية لها أنواع كالفراشة والحرة", difficulty: "medium" },
    { id: 270, emojis: "🥋🥋🥇", answers: ["التايكوندو"], category: "رياضة", hint: "رياضة دفاع عن النفس كورية تعتمد على الركلات", difficulty: "medium" },
    { id: 271, emojis: "🤺⚔️🛡️", answers: ["المبارزة"], category: "رياضة", hint: "رياضة قتالية بالسيوف الخفيفة ترتدي فيها أقنعة واقية", difficulty: "medium" },
    { id: 272, emojis: "🏹🎯🏅", answers: ["الرماية"], category: "رياضة", hint: "رياضة دقة تعتمد على إصابة الهدف بالقوس والسهم أو البندقية", difficulty: "medium" },
    { id: 273, emojis: "🏇🐎🏆", answers: ["فروسية"], category: "رياضة", hint: "رياضة ركوب الخيل والقفز على الحواجز", difficulty: "medium" },
    { id: 274, emojis: "🤸‍♀️🥇🤸‍♂️", answers: ["الجمباز"], category: "رياضة", hint: "رياضة تتطلب مرونة وتوازن عاليين جداً", difficulty: "medium" },
    { id: 275, emojis: "🤼‍♂️🤼‍♀️🥇", answers: ["المصارعة"], category: "رياضة", hint: "رياضة قتالية أولمبية تعتمد على طرح الخصم وتثبيته", difficulty: "medium" },
    { id: 276, emojis: "⛵🌊💨", answers: ["الشراع"], category: "رياضة", hint: "رياضة مائية تعتمد على توجيه القارب باستخدام قوة الرياح", difficulty: "medium" },
    { id: 277, emojis: "🚣‍♂️🛶🚣‍♀️", answers: ["التجديف"], category: "رياضة", hint: "رياضة مائية تستخدم فيها المجاديف لتحريك القارب بسرعة", difficulty: "medium" },
    { id: 278, emojis: "🤽‍♂️🤽‍♀️🤽", answers: ["كرة الماء"], category: "رياضة", hint: "لعبة جماعية تلعب في المسبح وتهدف لتسجيل الأهداف", difficulty: "medium" },
    { id: 279, emojis: "🏐🏖️🏐", answers: ["الكرة الطائرة"], category: "رياضة", hint: "رياضة جماعية تُلعب باليد ويفصل بين الفريقين شبكة عالية", difficulty: "medium" },
    { id: 280, emojis: "🏓🏓🏓", answers: ["تنس الطاولة"], category: "رياضة", hint: "رياضة مضرب تلعب على طاولة مقسمة بشبكة", difficulty: "medium" },
    { id: 281, emojis: "🏸🏸🏸", answers: ["تنس الريشة"], category: "رياضة", hint: "رياضة مضرب تستخدم فيها كرة خفيفة بريش", difficulty: "medium" },
    { id: 282, emojis: "⛳🏌️‍♂️🏌️‍♀️", answers: ["الجولف"], category: "رياضة", hint: "رياضة هادئة تهدف لإدخال الكرة في حفر صغيرة بأقل عدد ضربات", difficulty: "medium" },
    { id: 283, emojis: "🎳🎳🎳", answers: ["البولينج"], category: "رياضة", hint: "لعبة رمي كرة ثقيلة لإسقاط مجموعة من الدبابيس", difficulty: "medium" },
    { id: 284, emojis: "🥊🥊🥊", answers: ["الملاكمة"], category: "رياضة", hint: "رياضة قتالية تعتمد على اللكم بالقفازات", difficulty: "medium" },
    { id: 285, emojis: "🥋🥋🥋", answers: ["الجودو"], category: "رياضة", hint: "رياضة يابانية دفاع عن النفس تعتمد على طرح الخصم", difficulty: "medium" },
    { id: 286, emojis: "🥋🥋🥋", answers: ["الكاراتيه"], category: "رياضة", hint: "فن قتالي ياباني يعتمد على اللكمات والركلات", difficulty: "medium" },
    { id: 287, emojis: "🏉🏉🏉", answers: ["الرجبي"], category: "رياضة", hint: "لعبة جماعية عنيفة تشبه كرة القدم الأمريكية", difficulty: "medium" },
    { id: 288, emojis: "🏏🏏🏏", answers: ["الكريكت"], category: "رياضة", hint: "رياضة جماعية شعبية في الهند تعتمد على المضرب والكرة", difficulty: "medium" },
    { id: 289, emojis: "🏒🏒🏒", answers: ["الهوكي"], category: "رياضة", hint: "لعبة جماعية تلعب على الجليد أو العشب باستخدام عصا وكرة", difficulty: "medium" },
    { id: 290, emojis: "⚾⚾⚾", answers: ["البيسبول"], category: "رياضة", hint: "لعبة أمريكية شعبية تعتمد على رمي الكرة وضربها بالمضرب", difficulty: "medium" },
    { id: 291, emojis: "🎱🎱🎱", answers: ["البلياردو"], category: "رياضة", hint: "لعبة تلعب على طاولة ذات جيوب وتعتمد على إدخال الكرات الملونة", difficulty: "medium" },
    { id: 292, emojis: "🎯🎯🎯", answers: ["لعبة رمي السهام"], category: "رياضة", hint: "لعبة دقة تعتمد على رمي سهام صغيرة على لوحة دائرية مرقمة", difficulty: "medium" },
    { id: 293, emojis: "♟️♟️♟️", answers: ["الشطرنج"], category: "رياضة", hint: "لعبة ذكاء واستراتيجية تلعب على رقعة مقسمة إلى 64 مربع", difficulty: "medium" },
    { id: 294, emojis: "🎲🎲🎲", answers: ["النرد"], category: "العاب", hint: "مكعب مرقم يستخدم في العديد من ألعاب الطاولة والحظ", difficulty: "medium" },
    { id: 295, emojis: "🧩🧩🧩", answers: ["بازل"], category: "العاب", hint: "لعبة تركيب صور مقطعة لتكوين صورة كاملة", difficulty: "medium" },
    { id: 296, emojis: "🎮🕹️👾", answers: ["العاب فيديو"], category: "العاب", hint: "ألعاب إلكترونية تلعب على أجهزة مخصصة أو شاشات", difficulty: "medium" },
    { id: 297, emojis: "🎧🎤🎶", answers: ["بودكاست"], category: "منوعات", hint: "برامج صوتية مسجلة تبث عبر الإنترنت في مختلف المواضيع", difficulty: "medium" },
    { id: 298, emojis: "📚📖🔖", answers: ["كتاب"], category: "منوعات", hint: "مجموعة من الأوراق المطبوعة أو المخطوطة مجلدة معاً", difficulty: "medium" },
    { id: 299, emojis: "🎥🎬🎞️", answers: ["فيلم"], category: "افلام", hint: "عمل فني سينمائي يعرض قصة أو موضوع معين", difficulty: "medium" },
    { id: 300, emojis: "📺📺📺", answers: ["تلفزيون"], category: "منوعات", hint: "جهاز إلكتروني يعرض الصور المتحركة والأصوات", difficulty: "medium" }
];
